build_image:
  stage: build
  script:
    - docker build -t api:${CI_COMMIT_SHORT_SHA} -f packages/api/Dockerfile .

run_tests:
  stage: test
  script:
    - docker run -t api:${CI_COMMIT_SHORT_SHA} npm run lint
    - docker run -t api:${CI_COMMIT_SHORT_SHA} npm test

clean_up:
  stage: .post
  script:
    - docker rm $(docker ps -a -q) 2>&1 /dev/null
    - docker image rm api:${CI_COMMIT_SHORT_SHA}